version: '2'

services:
        web:
            image: nginx:latest
            ports:
                - "80:80"
                - "443:443"
            volumes:
                - ./:/var/www/
                - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
                - ./docker/logs/nginx:/var/log/nginx
            links:
                - backend
        backend:
            build:
                context: "./docker/php-fpm"
            ports:
                - "9080:9000"
            volumes:
                - ./:/var/www/
                - ./docker/config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
            links:
                - mysql:mysql
        mysql:
            build:
                context: "./docker/mysql"
            ports:
                - "3306:3306"
            volumes:
                - ./docker/.data/db:/var/lib/mysql
                - ./docker/config/mysql:/etc/mysql/conf.d
            environment:
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_DATABASE=app
        redis:
            image: redis:latest
            ports:
                - "6379:6379"
